image: Visual Studio 2019

platform:
    - x64
    - x86

configuration:
    - Release

test_script:
    - dotnet test "CodingProblemsTests\CodingProblemsTests.csproj" --configuration Release --no-build --output "Bin\Release\AnyCPU\"

before_build:
    - nuget restore